#! /usr/bin/env python3

import rospy
from contextlib import suppress
from kal2_perception.city_detector_node import CityDetectorNode

if __name__ == "__main__":
    with suppress(rospy.ROSInterruptException):
        node = CityDetectorNode()
        rospy.spin()
