#! /usr/bin/env python3

import rospy
from contextlib import suppress
from kal2_perception.direction_detector_node import DirectionDetectorNode

if __name__ == "__main__":
    with suppress(rospy.ROSInterruptException):
        node = DirectionDetectorNode()
        node.run()
