#! /usr/bin/env python3

import rospy
from contextlib import suppress
from kal2_perception.localization import LocalizationNode

if __name__ == "__main__":
    with suppress(rospy.ROSInterruptException):
        node = LocalizationNode()
        rospy.spin()
