#! /usr/bin/env python3

import rospy
from contextlib import suppress
from kal2_perception.sign_detector_node import SignDetectorNode

if __name__ == "__main__":
    with suppress(rospy.ROSInterruptException):
        node = SignDetectorNode()
        rospy.spin()
