#! /usr/bin/env python3

import rospy
from contextlib import suppress

from kal2_control.controller_node import ControllerNode

if __name__ == '__main__':
    with suppress(rospy.ROSInterruptException):
        controller_node = ControllerNode()
        rospy.spin()