#! /usr/bin/env python3

import rospy
from contextlib import suppress

from kal2_control.main_controller import MainControllerNode

if __name__ == '__main__':
    with suppress(rospy.ROSInterruptException):
        controller_node = MainControllerNode()
        rospy.spin()